[WEEK 4] Submit Homework
yujin1292/BreakingCodingTest pull request #25
Opened 2021-11-19 13:54 UTC by jeongiin

# Review
시간복잡도를 생각하면 BFS보다 DFS로 푸는 게 좋다고 하네요!
파이썬에서는 재귀함수 제한이 있어서 DFS 시에는
`sys.setrecursionlimit(10000)`
써주는 게 좋대요!
+ push 된 코드 중 3주차에 해당하는 내용은 수정된 게 없는데 파일을 삭제했다가 붙여넣기해서 뜨네요! 무시해주세요!

# Help!
다른 문제는 이상 없는데 2606만 런타임에러가 발생하는데 이유가 뭘까요..!?

2021-11-19 14:35 UTC, yujin1292 commented
> # Review
> 시간복잡도를 생각하면 BFS보다 DFS로 푸는 게 좋다고 하네요! 파이썬에서는 재귀함수 제한이 있어서 DFS 시에는 `sys.setrecursionlimit(10000)` 써주는 게 좋대요!

혹시 시간복잡도 이야기 좀더 이야기해줄수있을까요?! 문제마다 BFS가 DFS보다 시간복잡도가 좋지않은 케이스도 있어서요!

2021-11-19 14:55 UTC, yujin1292 reviewed
2606번 런타임에러 체크 다시 꼼꼼히 읽어볼게요 잠시만요~

2021-11-19 14:55 UTC, yujin1292 commented on HomeWork/JeongIn/4주차/BJ_2606.py
> +    graph[i].sort()
sort() 한 이유가 무엇인가요?!

2021-11-19 14:55 UTC, yujin1292 commented on HomeWork/JeongIn/4주차/BJ_11725.py
> +    print(visited[i])
visited 배열과 부모를 담는 배열 두개로 나누지않고 하나로 풀었네요 완전 지니어스~👍👍👍

2021-11-19 14:55 UTC, yujin1292 commented on HomeWork/JeongIn/4주차/BJ_2606.py
> +# 결과 값은 잘 나오는데 런타임 에러가 발생하는 이유는 뭘까요..
제출시 런타임 에러 발생이라는걸까요?! 보통 런타임 에러는 인덱스 범위 초과인 경우가 많아요

2021-11-19 15:00 UTC, yujin1292 commented on HomeWork/JeongIn/4주차/BJ_2606.py
> +    graph[i].sort()
sort 부분 삭제시 정답이네요~ 이부분 한번 체크해주세요!
파이썬 문법상 맞는지 잘모르겠네요

2021-11-19 15:02 UTC, yujin1292 requested changes
질문단것들 답변 부탁드리고 런타임 에러부분 한번 체크해주세요~  런타임에러 나는 문제 수정하면 approve 하겠습니다!

아주아주 수고많으셨습니다~~
![ThumbsUpInsideJobGIF](https://user-images.githubusercontent.com/27190708/142643996-bf3a4252-d03d-4eac-8b50-a780c8346d16.gif)

2021-11-19 15:02 UTC, yujin1292 commented on HomeWork/JeongIn/4주차/BJ_2606.py
> +    graph[i].sort()
sort 부분 삭제시 정답이네요~ 이부분 한번 체크해주세요!
파이썬 문법상 맞는지 잘모르겠네요

2021-11-21 11:59 UTC, jeongiin commented on HomeWork/JeongIn/4주차/BJ_2606.py
> +    graph[i].sort()
sort 삭제해보겠습니다!

2021-11-21 12:00 UTC, jeongiin commented on HomeWork/JeongIn/4주차/BJ_2606.py
> +# 결과 값은 잘 나오는데 런타임 에러가 발생하는 이유는 뭘까요..
sort 삭제해보겠습니다!
제출시 런타임 에러라는 이야기였습니다! 1부터 순서대로 그래프가 이어진다고 생각해서 sort를 했는데 다시 생각해보니 아닐 수도 있었네요 ㅠ Tree랑 헷갈리게 생각했나봐요!

2021-11-21 12:05 UTC, jeongiin commented
#25 2606번 sort 함수 삭제하고 commit 하였습니다!

2021-11-21 12:11 UTC, jeongiin commented
시간복잡도는 말씀대로 경험적인 부분인건데..!
DFS, BFS 둘 다로 풀 수 있는 문제가 많아서 찾아보니까

이동할 때마다 가중치가 붙어서 이동한다거나 이동 과정에서 여러 제약이 있을 경우 -> DFS
최단 거리 문제 -> BFS

라고 많이 리뷰되어있더라구요!
이유는 더 많이 풀면서 느껴봐야될 거 같아요~~~

2021-11-21 12:17 UTC, yujin1292 commented on HomeWork/JeongIn/4주차/BJ_2606.py
> +# 결과 값은 잘 나오는데 런타임 에러가 발생하는 이유는 뭘까요..
자식 노드들을 방문하는 순서에 제약이 있는 문제가 아니기 때문에 sort는 불필요합니다 !.. ( 가끔 제약 있는 문제가 있긴해요 )
sort함수에 의해서 런타임 에러가 나는것 같은데 제가 파이썬에 익숙치 않아서 정확한 이유는 모르겠네요 ㅠㅜ

2021-11-21 12:19 UTC, yujin1292 approved these changes

2021-11-21 12:23 UTC, yujin1292 commented
> 시간복잡도는 말씀대로 경험적인 부분인건데..! DFS, BFS 둘 다로 풀 수 있는 문제가 많아서 찾아보니까
> 
> 이동할 때마다 가중치가 붙어서 이동한다거나 이동 과정에서 
> 여러 제약이 있을 경우 -> DFS
>  최단 거리 문제 -> BFS
> 라고 많이 리뷰되어있더라구요! 이유는 더 많이 풀면서 느껴봐야될 거 같아요~~~



일단 모든 그래프들의 노드를 순회하는것은 보통 ```완전탐색```  이기 때문에 BFS 로 접근하든 DFS로 접근하든 문제는 풀 수있어요! 근데 ``` 백트래킹``` 을 위해서 어떠한 순회 방식을 선택하느냐에 따라서 효율성의 차이가 있을 수 있는거죠
백트래킹에 대해서는 이번주에 언급할 예정입니다 ! ! 

수업 내용 외에도 혼자서 공부하는 듯 한데 아주 좋아요`~~!!! ㅠ ㅠ 👍👍 
이번주도 수고많으셨고 스쿼시 머지로 머지 진행해주세요!

2021-11-21 13:21 UTC, merged