[week3] homework
yujin1292/BreakingCodingTest pull request #27
Opened 2021-11-21 13:40 UTC by arami98

1920 문제 시간초과가 나는데 재귀 호출로 풀면 안되는걸까요!?

2021-11-21 13:54 UTC, yujin1292 requested changes
시간 초과가 나는 이유는 무한하게 반복되는 계산이 있기 때문입니다!
바이너리 서치를 구현할 때 중단 조건이나 범위를 잘못 설정하게되면 종종 일어나는 일이에요~

관련 내용 수정방안 적어놨으니 확인해보시고 수정해주세요 ㅎㅎ

2021-11-21 13:54 UTC, yujin1292 commented on HomeWork/ARam/[week3]/[백준] 2798 블랙잭/2798.cpp
> +void black(int v, int sum, int cnt) {
이때는 dfs 진도 안나갔을때라 3중 for문으로 풀게 지도했는데 그레잇 이에요~

2021-11-21 13:54 UTC, yujin1292 commented on HomeWork/ARam/[week3]/[백준] 1920 수 찾기/1920.cpp
> +
b_search를 끝내는 부분에 문제가 있어서 무한하게 재귀호출을 하고있어서 시간초과가 나는거에요!

예를들어서 시작을 ```(0,5)``` 라고 해볼게요
그러면 mid가 2이기 때문에 ```(0,1)```, ```( 3,5)``` 요렇게 두갈래로 갈라지잖아요?

근데 여기서 ```(0,1)``` 부분을 한번더 계산해보면
mid는 0 이고,  ``` (0,-1)``` , ```(1,1)``` 이 재귀적으로 호출됩니다

근데 ```(0,-1)``` 은 중단되어야할 시점이지만 s==e가 아니기때문에 계속 계산이 진행돼요
따라서 중단 조건을 ``` s==e``` 가 아니``` s >= e``` 로 한다면? 원하는 시점에 중단이 잘 될태니 정답이 될거에요

2021-11-21 13:54 UTC, yujin1292 commented on HomeWork/ARam/[week3]/[백준] 1920 수 찾기/1920.cpp
> +	if (s == e) {
```suggestion
	if (s >= e) {
```

2021-11-21 13:56 UTC, yujin1292 commented on HomeWork/ARam/[week3]/[백준] 1920 수 찾기/1920.cpp
> +
b_search(s,e,n)을 간단히 (s,e) 로 표현했습니다~

2021-11-22 00:06 UTC, arami98 commented on HomeWork/ARam/[week3]/[백준] 1920 수 찾기/1920.cpp
> +
wow.. 설명 감사합니다! ! !

2021-11-22 02:25 UTC, yujin1292 approved these changes

2021-11-22 02:26 UTC, yujin1292 commented
수고하셨습니다~ 머지 진행해주세요 ! !

2021-11-22 03:05 UTC, yujin1292 requested changes
공유기 문제 빠져있는걸 깜빡하고 승인했는데 취소입니다~  이 문제 까지 커밋되면 Approve 할게요! ,,

2021-11-22 05:29 UTC, yujin1292 approved these changes
수고하셨습니다 머지 해주세요 ㅎㅎ
![BlacrswanGIF](https://user-images.githubusercontent.com/27190708/142805809-e8969085-ca08-4ba9-9b40-b3d5aa72c404.gif)
~

2021-11-22 06:40 UTC, merged