[WEEK 5] 과제 제출합니다!
yujin1292/BreakingCodingTest pull request #33
Opened 2021-11-28 02:46 UTC by jeongiin

이번주에 일이랑 일정이 유난히 많아서 N-Q 문제를 더 고민해보지 못했는데
알바 가기전에 우선 푼 문제까지 Push 합니다!

내일 있을 스터디에서는 푼 문제 모두 다 어떻게 풀어야 하는지 설명하는 걸까요?
아니면 설명하고 싶은 문제를 뽑아서 설명하면 되는걸까요?
후자 경우면 따로 간단하게나마 자료준비하면 좋을 거 같아서 미리 질문드립니다!

## homework review
- 2839 : while문으로 먼저 풀고 dfs도 고민해보았는데 스터디때 알려주신 알고리즘대로 생각이 안돼요..! 더 효율적이게 풀 수 있을 거 같은데 고민됩니다

- 1987 : 메모리 초과가 나는데 이유를 모르겠습니다! ㅠㅠ

2021-11-28 05:40 UTC, yujin1292 requested changes
N Queen 같은 경우는 같이 풀어봅시다! ㅠㅠ 
시간초과 나는 코드같은경우는 좀더 알아보고 코맨트 다시 달아드릴게요! 질문의도를 잘모르겠는 부분이 있어서 답글 부탁드릴게요~

같이 풀 문제는 아래와 같은데요, 어떻게 풀지 서로 공유하고 각자 풀어보는 시간을 가진후에 코드를 짜는 형식으로 가려고합니다!
![image](https://user-images.githubusercontent.com/27190708/143731080-f95c4ec3-4a53-483c-a395-e0267edd39a6.png)

2021-11-28 05:40 UTC, yujin1292 commented on HomeWork/JeongIn/5주차/BJ_1389.py
> +                bacon[i] = bacon[pop] + 1
굿 굿 좋아요~ 혹시 qsize로 끊어 계산하는방법은 이해했나요?

2021-11-28 05:40 UTC, yujin1292 commented on HomeWork/JeongIn/5주차/BJ_2839.py
> +    print(ans)
음.. 정답이 나온 코드인데 지난번에 설명한방법으로 못풀겠다는건가요>?..

2021-11-28 08:01 UTC, jeongiin commented on HomeWork/JeongIn/5주차/BJ_2839.py
> +    print(ans)
넹 맞습니다! 저 코드로 정답은 나오는데 스터디때 써주신 알고리즘으로 푸는 방법도 궁금하다는 의미였고 나중에 C++ 코드 올려주시면 확인해보겠습니다~!!

2021-11-28 08:02 UTC, jeongiin commented on HomeWork/JeongIn/5주차/BJ_1389.py
> +                bacon[i] = bacon[pop] + 1
넵넵!

2021-11-28 08:11 UTC, yujin1292 commented on HomeWork/JeongIn/5주차/BJ_2839.py
> +    print(ans)
아하~~
아래에 설명했던 방식이랑 비슷한 코드(BFS로 품)  남겨둘태니 읽어보세요 ~!!
```c++
#include <algorithm>
#include <iostream>
#include <vector>
#include <queue>
using namespace std;

int N;
int visit[5001];  // visit[a] = 1 or 0 -> a kg 챙기는 계산을 했는지 체크

int main() {
	ios_base::sync_with_stdio(false);
	cin.tie(NULL);
	cout.tie(NULL);

	cin >> N;

	int cnt = 0;
	int curr, next;
	queue<int> q;
	visit[0] = 1;
	q.push(0);

	while (!q.empty()) {
		int qsize = q.size();
		while (qsize--) {
			curr = q.front();
			q.pop();

			if (curr == N) { // 답을 구했으니 출력하고 프로그램 종료
				cout << cnt << "\n";
				return 0;
			}
                        // 3kg 챙김
			next = curr + 3;
			if (next <= N) {
				if (!visit[next]) {
					q.push(next);
					visit[next] = 1;
				}
			}
                        // 5kg 챙김
			next = curr + 5;
			if (next <= N) {
				if (!visit[next]) {
					q.push(next);
					visit[next] = 1;
				}
			}

		}
		cnt++;
	}
	cout << -1 << "\n";
	return 0;
}
```

2021-11-28 08:14 UTC, yujin1292 commented on HomeWork/JeongIn/5주차/BJ_2839.py
> +    print(ans)
dfs로 풀 경우에는 `if (curr == N) ` 일 때 재귀함수가 끝나게되는데, 현재 문제에서는 `제일 적게` 챙기는 방안을 묻고있으니 dfs보다는 bfs가 좀더 합리적이에요 

완전 탐색시 dfs와 bfs중 선택하는 방향성에대해 설명을 제대로 안한것같아 수업때 다시 언급할게요

2021-11-28 08:16 UTC, yujin1292 commented
Queen 문제는 수업때 같이 풀어볼태니 나중에 같이 푼문제랑 합쳐서 PR 하도록 하고 머지해도 좋을것같아요!

수고많으셨습니다 👍👍👍

2021-11-28 08:16 UTC, yujin1292 approved these changes

2021-11-28 13:25 UTC, jeongiin commented on HomeWork/JeongIn/5주차/BJ_2839.py
> +    print(ans)
확인했습니다!

2021-11-29 06:56 UTC, jeongiin commented
@yujin1292 Queen 유진퀸.. 아니 유진킹.. 아니 갓유진~~!!
설명듣고 광명찾아서 푼 9663 문제 추가했습니다~~~><

2021-11-29 07:06 UTC, yujin1292 approved these changes
### 아주아주아주아주 좋아요~~~~~~
### 머지해주세요!!

![EnugantiGadinatorGIF](https://user-images.githubusercontent.com/27190708/143823008-5904cdc0-7968-4c10-aa2a-1fab9acc283c.gif)

2021-11-29 07:10 UTC, merged