Week 10 제출입니당
yujin1292/BreakingCodingTest pull request #46
Opened 2022-01-21 14:06 UTC by j-miiin

이번주 과제는 지난주에 개념 공부했던 코드들을 그대로 사용해서 풀 수 있어서 수월하게 풀었습니당! 
다익스트라 알고리즘을 두 번 사용해서 푸는 문제에서 쪼끔 헤맸는데 
간선 정보를 거꾸로 받아서 저장하는 방법을 떠올리기가 쉽지 않았던 것 같아요
풀고 나서도 완벽하게 이해 된 기분이 아니라서 종이에 계속 그래프 그리면서 계산했씀미당.. 
우선순위 큐를 이용한 다익스트라 알고리즘 내용은 아직 공부 중이라 정리 다 하면 리드미에 추가해보겠습니다~!
다음주도 빠이팅~~~

2022-01-22 05:29 UTC, yujin1292 requested changes
이번주도 수고많으셨습니다! 아래에 제가 적은 코맨트 확인하시고 수정 후 커밋해주세요

---
1238 파티 문제 정답처리되었긴 하지만, 접근방법이 잘못된것같아요 ㅠㅠ
다시한번 풀어보시겠어요..?

> ### 1238 파티 
> N개의 숫자로 구분된 각각의 마을에 한 명의 학생이 살고 있다.
> 
> 어느 날 이 N명의 학생이 X (1 ≤ X ≤ N)번 마을에 모여서 파티를 벌이기로 했다. 이 마을 사이에는 총 M개의 **단방향** 도로들이 있고 i번째 길을 지나는데 Ti(1 ≤ Ti ≤ 100)의 시간을 소비한다.
> 
> 각각의 학생들은 파티에 참석하기 위해 걸어가서 다시 그들의 마을로 돌아와야 한다. 하지만 이 학생들은 워낙 게을러서 최단 시간에 오고 가기를 원한다.
> 
> 이 도로들은 **단방향이기 때문에 아마 그들이 오고 가는 길이 다를지도 모른다.** N명의 학생들 중 오고 가는데 가장 많은 시간을 소비하는 학생은 누구일지 구하여라.
> 

N개의 마을에서 X로 가는 최단거리를 구해야하니  방법은 두가지가될것같아요
1. `start(1~N)` -> `X`   `X` -> `dest(1~N)` 형태의 다익스트라 을통한 최댓값 계산 
2. 플로이드와샬로 최단거리를 모두 구한후 `graph[i][X] + graph[X][i] ( i in 1~N) `  의 값들 중 최댓값

---
전반적으로 INF 값을 MAX_VALUE로 풀고있네요 ㅠ 습관적으로 이렇게 풀다보면 애먹는 날이 언젠간 올거라 생각이 들어요.. 문제별로  특성을 파악해서 INF값을 어느정도로 줘야할지 파악해보세요

2022-01-22 05:29 UTC, yujin1292 commented on Season 02/homework/JeongMin/week 10/week10_1238.java
> +        reverse_graph = new ArrayList<ArrayList<Node>>();
간선방향을 왜 바꿔서 풀었을까요?..

2022-01-22 05:29 UTC, yujin1292 commented on Season 02/homework/JeongMin/week 10/week10_1238.java
> +        reverse_graph = new ArrayList<ArrayList<Node>>();
> 이 도로들은 단방향이기 때문에 아마 그들이 오고 가는 길이 다를지도 모른다.
 
라고 적혀있기때문에` a->b`의 도로가 있으면 `b->a` 는 시간이 아에 다르거나 존재하지않을수도있어요

예제1 에서도

```
1 2 4
2 1 1
```
으로 방향이 다를때 가중치가 다르기 때문에 단순히 간선방향을 바꿔서 푸는건 맞지않는것같아요

2022-01-22 05:29 UTC, yujin1292 commented on Season 02/homework/JeongMin/week 10/week10_1238.java
> +        reverse_Dijkstra(N, start);
1~N 지점 에서 X 마을로 가야하는 경우다 보니  플로이드와샬이 좀 더 적합할것같아요

2022-01-22 05:29 UTC, yujin1292 commented on Season 02/homework/JeongMin/week 10/week10_1753.java
> +            dist[i] = Integer.MAX_VALUE;
INF값을 MAX_VALUE 대신 다른 특정값으로 진행해주세요

2022-01-22 15:14 UTC, j-miiin commented on Season 02/homework/JeongMin/week 10/week10_1238.java
> +        reverse_graph = new ArrayList<ArrayList<Node>>();
저는 학생이 오고 가는 거리를 두 가지로 나눴을 때 
(1) i (1~N)번 마을에서 X번 마을까지 이동
(2) X번 마을에서 i(1~N)번 마을까지 이동 
이렇게 된다고 봤는데요, 여기서 reverse 함수를 이용한 부분은 (1) 입니다!!
(1)을 그대로 계산하려고 하면 다익스트라 알고리즘을 N-1번 반복해야 하기 때문에 
간선의 방향을 바꾸고 X번 마을에서 i(1~N)번 마을까지 이동하는 방식으로 바꿔 계산했습니당
이렇게 하면 X번 마을에서 시작하는 다익스트라 알고리즘 한번으로 계산이 가능하니까요!
플로이드 와샬 알고리즘을 사용하지 않은 이유는 N 값을 고려해서 다익스트라 알고리즘이 더 효율적일 거라고 생각했습니당 사실 음수 가중치 없다는거 읽고 다익스트라 쓰기로 마음 먹은건 비밀

2022-01-22 15:18 UTC, j-miiin commented on Season 02/homework/JeongMin/week 10/week10_1753.java
> +            dist[i] = Integer.MAX_VALUE;
넹ㅠㅠ INF 값을 어떻게 적절하게 정할지 감을 못잡겠어서 일단은 MAX_VALUE를 썼습니당..! 이 부분은 더 공부해보겠습니다!!

2022-01-23 05:21 UTC, yujin1292 commented on Season 02/homework/JeongMin/week 10/week10_1238.java
> +        reverse_graph = new ArrayList<ArrayList<Node>>();
아~~~~~~ 이해했어요~

아에 생각치도 못한 접근법이네요 귯!! 👍👍👍👍👍

2022-01-23 05:28 UTC, yujin1292 approved these changes
제가 이해를 잘못했었네요! ! ! !
너무 수고많으셨고  한수 배웠습니다 😹  이 맛에 남의 코드 참고하는것 아닐까용..
INF 선정하는 기준에 대해서 제 의견도 남겼으니 확인해주시고 

스쿼시 머지해주세요 ! ! 

![ThumbsUpInsideJobGIF](https://user-images.githubusercontent.com/27190708/150666238-b00cc55b-8e77-49e2-aa8d-6210a72deaae.gif)

2022-01-23 05:28 UTC, yujin1292 commented on Season 02/homework/JeongMin/week 10/week10_1753.java
> +                    dist[adjNode.idx] = dist[nodeIdx] + adjNode.cost;
INF 값이 문제가 되는 경우가 이런경우에요!

만약에 dist[nodeIdx] 도 INF, adjNode.cost 가 3이라면, 
INF + 3 은 결국 INF 가 되어야되는데 오버플로우로 인해서 음수로 바뀌거나 작은 수로 변경되면 
값이 이상해지죠 

제 경험상 두 비용을 더했을때 오버플로우가 되지않는 선에서 INF를 선정하는게 맞는것 같아요

2022-01-23 05:36 UTC, yujin1292 commented on Season 02/homework/JeongMin/week 10/week10_1238.java
> +        reverse_graph = new ArrayList<ArrayList<Node>>();
@jeongiin 
 정민이가 푼 풀이가 멋져서 한 번 읽어봤으면 해서 언급합니다!~~~~

2022-01-23 08:35 UTC, yujin1292 commented on Season 02/homework/JeongMin/week 10/week10_1753.java
> +            dist[i] = Integer.MAX_VALUE;
저는 어떻게 INF값을 설정하냐면, 만약 구해야하는 A->B로 가는 경로가 모든 마을을 거쳐가야하는데 모두 최대비용을 가진 도로들이면 최악의 경우이지 않겠어요?..

그래서 저는 마을의 개수 x 최대경로값 + 1 정도로 진행한답니다 ..

2022-01-31 06:42 UTC, merged